### ISSUE TITLE
Error installing: ck install package:lib-python-qiskit

### ISSUE THREAD

**Issue by junmendoza** [ctuning/ck-qiskit#5] opened 2018-10-04 17:18 UTC
**OS:** Ubuntu 18.04.1 LTS 

**Followed steps here:**
https://github.com/ctuning/ck-qiskit

When i get to the step to install qiskit:
ck install package:lib-python-qiskit

**I get this on the terminal:**
Cleanup: removing /home/xxx/CK-TOOLS/lib-python-qiskit-compiler.python-3.6.5-linux-64/python_deps_site
Installing 'qiskit' and its dependencies to '/home/xxx/CK-TOOLS/lib-python-qiskit-compiler.python-3.6.5-linux-64/python_deps_site/lib/python3.6/site-packages' ...
ERROR: Can not combine '--user' and '--prefix' as they imply different installation locations
Error: installation failed!
CK error: [package] package installation failed!

How can this be fixed?

Thanks,
Jun

**Comment by ens-lg4** [comment] 2018-10-04 17:36
Dear @junmendoza ,

I haven't been able to reproduce it so far (on Ubuntu 16.04).

But we have been notified by IBM QuantumExperience providers that they have bumped up the Qiskit version to 0.6, which introduced a few incompatible changes. To protect ourselves from this change we have amended our code and the docs (slighly). From the command you were trying to run I can see it was in the older version of docs.

So while I'm trying to replicate your problem, could you please try the following steps:
First, run `ck pull all` to pick up the latest changes, then `ck clean env -f` to clean up the state and start again (following the updated docs). It may "just work" or it may not. Either way please comment - I'll leave this issue open.

**Comment by junmendoza** [comment] 2018-10-04 17:47
Ive tried your suggestion and attempted to reinstall and run into the same issue.
The only thing that looks out of place during installation is when i run: 
`sudo python3 -m pip install ck`

**I get this:**
The directory '/home/xxx/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/xxx/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

Any idea with that? is it related?

I know the installation fails because when i run:
`ck run program:qiskit-demo --cmd_key=quantum_coin_flip`

It asks me to install the missing components:
```
More than one package found:
0) lib-python-qiskit-0.5.7  Version 0.5.7  (11c284540a3a9cf2)
1) lib-qiskit-0.5.4  Version 0.5.4  (install QISKit, f18be622f743068a)
2) lib-qiskit  Version master  (install QISKit, 64bfb4526be318ee)
3) lib-python-qiskit (54de9844665a936e)
```
Which will go back to the original issue as it requires calling this again:
`ck install package:lib-python-qiskit`

**Comment by ens-lg4** [comment] 2018-10-04 18:09
Thanks for trying!
It looks like the issue actually concerns your permissions to run `pip` under `sudo`. On some systems you don't need `sudo` (in fact, it turns into a problem).

Could you please try just `python3 -m pip install ck` without `sudo` - will it work?

If not (only if not), please also try `python3 -m pip install ck --user`

**Comment by junmendoza** [comment] 2018-10-04 18:23
@ens-lg4 
Doing this fixed the 2nd issue: `python3 -m pip install ck`

After some trial and error, adding sudo when installing qiskit fixed the first issue also: 
`sudo ck install package:lib-python-qiskit-0.5.7`

Thank for the suggestions, the demos now work!

Closing this issue

**Comment by gfursin** [comment] 2018-10-04 19:50
Hi guys, I am reopening this issue, because I see some incorrect way of using CK. 

The problem "ERROR: Can not combine '--user' and '--prefix' as they imply different installation locations" is a known problem with an older pip, and normally not related to CK or its installation (whether sudo or user). Can you please tell us what is your pip version:
```
$ python3 -m pip --version
```

Can you also please provide a log with:
```
$ ck show env
```

Furthermore, please avoid to use sudo with the ck itself (sudo ck) since CK will now create new temporal CK entries in the user space under root. It was never intended to be used like that. 

So, I suggest you to clean your CK installation (remove everything from $HOME/CK - you may now need sudo because you will have CK entries under root), then upgrade pip (sudo python3 -m pip install --upgrade pip), and then please try again with "ck install package:lib-python-qiskit" ...

Normally, it should work. If not, we need to check it again but the problem is normally orthogonal to CK because CK just calls a bash script which then calls pip to install another package, so CK is in a separate process and is not involved at this stage ...

Let's try to check/fix it tomorrow ... Thanks!

**Comment by psyhtest** [comment] 2018-10-05 08:23
We should also mention a `pip`-free installation option here: https://github.com/ctuning/ck#linuxmacos

**Comment by psyhtest** [comment] 2018-10-05 08:34
@kalyazin Are you having the same problem on Gentoo?

**Comment by kalyazin** [comment] 2018-10-05 11:45
> @kalyazin Are you having the same problem on Gentoo?

`$ ck install package:lib-python-qiskit-0.5.7`
`Installing 'qiskit' and its dependencies to '/home/kain/CK-TOOLS/lib-python-qiskit-0.5.7-compiler.python-3.6.5-linux-64/python_deps_site/lib/python3.6/site-packages' ...`
`ERROR: (Gentoo) Please run pip with the --user option to avoid breaking python-exec`
`Error: installation failed!`
`CK error: [package] package installation failed!`

`$ PIP_USER=1 ck install package:lib-python-qiskit-0.5.7`
`Installing 'qiskit' and its dependencies to '/home/kain/CK-TOOLS/lib-python-qiskit-0.5.7-compiler.python-3.6.5-linux-64/python_deps_site/lib/python3.6/site-packages' ...`
`ERROR: Can not combine '--user' and '--prefix' as they imply different installation locations`
`Error: installation failed!`
`CK error: [package] package installation failed!`

`$ pip --version`
`pip 10.0.1 from /usr/lib64/python2.7/site-packages/pip (python 2.7)`

**Comment by ens-lg4** [comment] 2018-10-05 12:23
How come we even allow Python2 and its pip???

**Comment by ens-lg4** [comment] 2018-10-05 12:25
Sorry, I just realised you ran pip by hand. We advise never to do it, because there is no guarantee python and pip will match (and they should, because different versions keep their libraries separately).

Please run `python3 -m pip version` instead.

**Comment by kalyazin** [comment] 2018-10-05 14:17
> python3 -m pip version

`$ python3 -m pip --version`
`pip 10.0.1 from /usr/lib64/python3.6/site-packages/pip (python 3.6)`

**Comment by psyhtest** [comment] 2018-10-05 14:34
Hmm, installing QISKit-0.5.7 worked for me on RK3399 (aarch64) with Ubuntu 16.04:
```
$ ck install package:lib-python-qiskit-0.5.7
```
with the same version of `pip`:
```
anton@firefly:~$ python3 -m pip --version                                                            
pip 10.0.1 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)
```

**Comment by psyhtest** [comment] 2018-10-05 14:37
..but failed on HiKey960 with Debian 9:
```
$ ck install package:lib-python-qiskit-0.5.7
...
Installing 'qiskit' and its dependencies to '/home/anton/CK_TOOLS/lib-python-qiskit-0.5.7-compiler.python-3.5.3-linux-64/python_deps_site/lib/python3.5/site-packages' ...
ERROR: Can not combine '--user' and '--prefix' as they imply different installation locations
Error: installation failed!
CK error: [package] package installation failed!
```
with an older version `pip`:
```
anton@hikey962:~/CK_REPOS$ python3 -m pip --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)
```

**Comment by psyhtest** [comment] 2018-10-05 15:04
However, specifying `PIP_USER=0` on HiKey960 allowed me to avoid sudden death from the confict:
```
$ PIP_USER=0 ck install package:lib-python-qiskit-0.5.7
```
(still waiting for installation to complete though).

**Comment by kalyazin** [comment] 2018-10-05 15:07
We definitely know that --user and --prefix cannot be set at the same time.
Additionally, for Gentoo (at least mine) pip needs to have --user set. Which makes impossible to use --prefix.

**Comment by psyhtest** [comment] 2018-10-05 15:15
But would you mind trying that? This would temporarily disable `pip --user` and allow us to install QISKit under the user home directory (`$HOME/CK`) with `pip --prefix` without changing a single line in our installation scripts.

**Comment by kalyazin** [comment] 2018-10-05 15:36
I think, 1st case already covers PIP_USER=0, because --user doesn't seem to be set by default in my pip:
https://github.com/ctuning/ck-qiskit/issues/5#issuecomment-427337972

**Comment by kalyazin** [comment] 2018-10-05 15:36
I will test it shortly though.

**Comment by kalyazin** [comment] 2018-10-05 15:46
Tested. Exactly same:
`ERROR: (Gentoo) Please run pip with the --user option to avoid breaking python-exec`

**Comment by junmendoza** [comment] 2018-10-05 23:01
@gfursin 

Ran: `python3 -m pip --version`
Got: `pip 18.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)`

I removed /home/CK then ran: `sudo python3 -m pip install --upgrade pip` 

Then the following:
```
ck pull repo:ck-qiskit
ck install package:lib-python-qiskit-0.5.7
```

It also works and i can run the demos.
Thanks for pointing out the correct way of installing it.

**Comment by gfursin** [comment] 2018-10-06 07:09
You are welcome, @junmendoza . We think about adding detection of pip version to suggest upgrade (instead of having an error). I am closing this ticket for now.

**Closed as completed by gfursin** 2018-10-06 07:09 UTC

**Comment by kalyazin** [comment] 2018-10-06 07:19
After upgrading pip to 18.1 I observe the following:

`ck install package:lib-python-qiskit-0.5.7`

```
Setting up environment for installed package ...
  (full path = /home/kain/CK-TOOLS/lib-python-qiskit-0.5.7-compiler.python-3.6.5-linux-64/build/qiskit/__init__.py)

  Software entry found: lib.qiskit (126e8e93a4041e7a)

  -----------------------------------
  Resolving software dependencies ...

*** Dependency 1 = python (Python 3):

    Resolved. CK environment UID = 49d5d3d26450cb0a (detected version 3.6.5)
  -----------------------------------
CK error: [package] software not found in a specified path (/home/kain/CK-TOOLS/lib-python-qiskit-0.5.7-compiler.python-3.6.5-linux-64/build/qiskit/__init__.py)
```
Softlink `/home/kain/CK-TOOLS/lib-python-qiskit-0.5.7-compiler.python-3.6.5-linux-64/build` is indeed broken, pointing at non-existing `/home/kain/CK-TOOLS/lib-python-qiskit-0.5.7-compiler.python-3.6.5-linux-64/python_deps_site/lib/python3.6/site-packages`.

Any ideas?

**Comment by kalyazin** [comment] 2018-10-06 09:56
A workaround from @ens-lg4:
`PIP_LIB_SUFFIX=64 ck install package:lib-python-qiskit-0.5.7` .
